[versions]
minecraft = "26.2"

loader = "0.19.3"
fabric-api = "0.158.0+26.2"

bstats = "3.2.1"

[libraries]
# fabric
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Other
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# Plugins
[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version = "1.17-SNAPSHOT" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "3.1.0" }
paperweight = { id = "io.papermc.paperweight.userdev", version = "2.0.0-beta.+" }
shadow = { id = "com.gradleup.shadow", version = "9.6.1" }